#
# TEST PURPOSE/DESCRIPTION:
# ------------------------
#
# This test is to ensure that 
#

RUN_ENVIR="community"
PREEXISTING_DIR_METHOD="rename"
#
# This test assumes the forecast files will be generated by running a 
# single (i.e. deterministic) forecast.  Thus, specify the parameters 
# needed to run such a forecast.
#
PREDEF_GRID_NAME="RRFS_CONUS_25km"
LAYOUT_X="10"
LAYOUT_Y="4"
CCPP_PHYS_SUITE="FV3_GFS_2017_gfdlmp"

EXTRN_MDL_NAME_ICS="GSMGFS"
EXTRN_MDL_NAME_LBCS="GSMGFS"
USE_USER_STAGED_EXTRN_FILES="TRUE"

DATE_FIRST_CYCL="20190520"
DATE_LAST_CYCL="20190520"
CYCL_HRS=( "00" )

FCST_LEN_HRS="6"
LBC_SPEC_INTVL_HRS="6"
#
# This test assumes the observation files are staged.  Thus, deactivate
# the GET_OBS_... tasks and instead instead specify the obs staging
# directories.
#
RUN_TASK_GET_OBS_CCPA="FALSE"
CCPA_OBS_DIR="/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/DTC_ensemble_task/test_get_obs_data/ccpa/proc"
RUN_TASK_GET_OBS_MRMS="FALSE"
MRMS_OBS_DIR="/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/DTC_ensemble_task/test_get_obs_data/mrms/proc"
RUN_TASK_GET_OBS_NDAS="FALSE"
NDAS_OBS_DIR="/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/DTC_ensemble_task/test_get_obs_data/ndas/proc"
#
# Run deterministic vx on each member of the forecast ensemble (i.e. set
# RUN_TASKS_VXDET to "TRUE"), but do not run vx on the ensemble as a
# whole (i.e. set RUN_TASKS_VXENS to "FALSE").
#
RUN_TASKS_VXDET="TRUE"
RUN_TASKS_VXENS="FALSE"
#
# MET and METplus paths.  Move these to the machine files?
#
METPLUS_PATH="/contrib/METplus/METplus-4.1.1"
MET_INSTALL_DIR="/contrib/met/10.1.1"
#
# The following are for the old versions of the vx tasks.  Should remove
# at some point.
#
INCLUDE_OLD_VX_TASKS_IN_XML="FALSE"

RUN_TASK_VX_GRIDSTAT="TRUE"
RUN_TASK_VX_POINTSTAT="TRUE"
RUN_TASK_VX_ENSGRID="TRUE"
RUN_TASK_VX_ENSPOINT="TRUE"

WTIME_VX_ENSPOINT="08:00:00"
WTIME_VX_ENSGRID="08:00:00"
