#
# TEST PURPOSE/DESCRIPTION:
# ------------------------
#
# This test is to ensure that 
#

RUN_ENVIR="community"
PREEXISTING_DIR_METHOD="rename"

DATE_FIRST_CYCL="20190701"
DATE_LAST_CYCL="20190701"
CYCL_HRS=( "06" )

FCST_LEN_HRS="6"
#
# This test assumes the forecast files are staged (i.e. not generated by
# running the forecast model as part of this experiment ).  Thus, turn
# off the forecast, post-processing, and other tasks that are not needed
# for generation of post-processed forecast files.
#
RUN_TASK_MAKE_GRID="FALSE"
RUN_TASK_MAKE_OROG="FALSE"
RUN_TASK_MAKE_SFC_CLIMO="FALSE"
RUN_TASK_GET_EXTRN_ICS="FALSE"
RUN_TASK_GET_EXTRN_LBCS="FALSE"
RUN_TASK_MAKE_ICS="FALSE"
RUN_TASK_MAKE_LBCS="FALSE"
RUN_TASK_RUN_FCST="FALSE"
RUN_TASK_RUN_POST="FALSE"
#
# Since the forecast files are staged, specify the base staging directory.
# Also, since these staged files use a naming convention differs from
# the default convention in the SRW App, explicitly specify their
# subdirectory and file name templates.
#
VX_FCST_INPUT_BASEDIR="/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/DTC_ensemble_task/staged/fcst_ens"
#
# This test assumes the observation files are staged.  Thus, deactivate
# the GET_OBS_... tasks and instead specify the obs staging directories.
#
RUN_TASK_GET_OBS_CCPA="FALSE"
CCPA_OBS_DIR="/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/DTC_ensemble_task/staged/obs/ccpa/proc"

RUN_TASK_GET_OBS_MRMS="FALSE"
MRMS_OBS_DIR="/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/DTC_ensemble_task/staged/obs/mrms/proc"

RUN_TASK_GET_OBS_NDAS="FALSE"
NDAS_OBS_DIR="/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/DTC_ensemble_task/staged/obs/ndas/proc"
#
# This test assumes that the forecast(s) to be verified is an ensemble
# forecast, i.e. that the post-processed forecast files are in an ensemble
# directory structure.  Thus, turn the flag that specifies this on and
# specify the number of members in the ensemble.
#
IS_ENS_FCST="TRUE"
NUM_ENS_MEMBERS="2"
#
# Run deterministic vx on each member of the forecast ensemble.
#
RUN_TASKS_VXDET="TRUE"
#
# Run vx on the ensemble as a whole.
#
RUN_TASKS_VXENS="TRUE"
#
# Specify other vx parameters.
#
# ENS_TIME_LAG_HRS is the time-lagging that the vx tasks should assume
# for each ensemble member (in units of hours).
ENS_TIME_LAG_HRS=( "6" "0" )
# NET and POST_OUTPUT_DOMAIN_NAME are needed if assuming that the staged
# forecast files use the default (post-processed) forecast file naming
# convention and in constructing the default value of VX_FCST_MODEL_NAME
# if an explicit value for it has not been specified, both of which are
# true for this test.  (VX_FCST_MODEL_NAME is the (base) forecast model
# name to use in the vx output, both in the output file names and in
# their contents.)
NET="rrfs"
POST_OUTPUT_DOMAIN_NAME="rrfs_conus_25km"
#
# MET and METplus paths.  Move these to the machine files?
#
METPLUS_PATH="/contrib/METplus/METplus-4.1.1"
MET_INSTALL_DIR="/contrib/met/10.1.1"
#
# The following are for the old versions of the vx tasks.  Should remove
# at some point.
#
INCLUDE_OLD_VX_TASKS_IN_XML="FALSE"

RUN_TASK_VX_GRIDSTAT="TRUE"
RUN_TASK_VX_POINTSTAT="TRUE"
RUN_TASK_VX_ENSGRID="TRUE"
RUN_TASK_VX_ENSPOINT="TRUE"

WTIME_VX_ENSPOINT="08:00:00"
WTIME_VX_ENSGRID="08:00:00"
